### ISSUE TITLE
为什么图片地址生成了还是看不到图片啊？

### ISSUE THREAD

**Issue by cooper1x** [jiwenxing/qiniu-image-tool-win#1]
都是按照教程上一步步配置的，貌似是测试域名的问题，看了那个空间里面也没有上传的文件。。。
![](http://opmtdotp9.bkt.clouddn.com/201705081946_816.png)

**Comment by cooper1x** [comment]
Open account file failed, open .qshell\account.json: The system cannot find the path specified., please use `account` to set AccessKey and SecretKey first
系统找不到指定的路径。

**Comment by jiwenxing** [comment]
你是不是上传的是截图，你先上传一个本地图片看能不能成功，如果成功的话你再上传截图，这个问题我明天修复一下

**Comment by cooper1x** [comment]
本地的也不行呢，报错如下：
```
Uploading G:\Users\Cooper\Desktop\9999.png => markdown : 201705082057_244.png ...
Progress: 100%
Put file error, 400 incorrect region, please use up-z2.qiniu.com, Reqid: 0wUAAGp6j6faorwU
Last time: 0.43 s, Average Speed: 415.6 KB/s
```

**Comment by jiwenxing** [comment]
把 up-z2.qiniu.com 加到 RunWait, %comspec% /c qshell account %ACCESS_KEY% %SECRET_KEY% && qshell fput %BUCKET_NAME% %filename% %clipboard% 这行代码的最后面，然后reload一下脚本试一下

**Comment by cooper1x** [comment]
在末尾出空格后加了这个网址还是报错。。。
```
Uploading G:\Users\Cooper\Desktop\9999.png => markdown : 201705082109_842.png ...
Progress: 100%
Put file error, 400 incorrect region, please use up-z2.qiniu.com, Reqid: WHQAAMS5R6GLo7wU
Last time: 0.22 s, Average Speed: 805.6 KB/s
```

**Comment by jiwenxing** [comment]
刚才写的忘了加http头，我更新了一下刚才的回答，是加http://up-z2.qiniu.com，然后上传本地图片
这个问题是因为使用默认的uphost有问题，错误提示里给出了推荐的uphost，参考：https://github.com/qiniu/qshell/wiki/fput

**Comment by cooper1x** [comment]
本地图片复制后用快捷键粘贴命令行里面显示成功，但Typora里面没有内容。
```
Uploading G:\Users\Cooper\Desktop\9999.png => markdown : 201705082115_271.png ...
Progress: 100%
Put file G:\Users\Cooper\Desktop\9999.png => markdown : 201705082115_271.png ( Fj4CNKrTpkYSkpyvXbbucSmAnBN_ ) success!
Last time: 0.53 s, Average Speed: 338.0 KB/s
```
使用截图后粘贴，报错信息如下：
```
Bild gefunden. 395x219 Pixel.
Local file error GetFileAttributesEx C:\Program: The system cannot find the file specified.
系统找不到指定的路径。
```

**Comment by jiwenxing** [comment]
Typora里面没有内容是什么意思？截图这个错误还没有遇到过，家里没有windows环境，明天我排查一下
另外你的的截图工具是什么，系统是否自带powershell，版本号是多少

**Comment by cooper1x** [comment]
用到是QQ自带的截图，没有powershell只有cmd。没有内容就是按了快捷键粘贴后除了弹出命令行外不起作用，什么内容也没有粘贴出来。

**Comment by jiwenxing** [comment]
可以加qq412516590聊

**Comment by jiwenxing** [comment]
问题已解决，原因如下：
1. 由于七牛区域原因，默认uphost无法上传，需要按照报错信息修改uphost配置，我的华北和华东bucket使用默认uphost则可以上传
2. WORKING_DIR 工作路径设置不能包含类似`Program Files`带有空格的路径

**Comment by MaNongkuxingseng** [comment]
Local file error GetFileAttributesEx http://ov0z8zu6l.bkt.clouddn.com/2017082116
12_246.png): The filename, directory name, or volume label syntax is incorrect.
参数都照着改过了，出现这样的问题。求解。
