### ISSUE TITLE
Powershell提升权限后依旧提示权限不足

### ISSUE THREAD

**Issue by Daniels5** [jiwenxing/qiniu-image-tool-win#3]
在WIN10出现了这样的错误：
set-executionpolicy : 对注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell”的
访问被拒绝。 要更改默认(LocalMachine)作用域的执行策略，请使用“以管理员身份运行”选项启动 Windows PowerShell。要更改当
前用户的执行策略，请运行 "Set-ExecutionPolicy -Scope CurrentUser"。

PS权限更改为remotesigned之后还是持续弹出同样的提醒。请教一下怎么处理呢？谢谢

**Comment by jiwenxing** [comment]
你在ps中执行`Get-ExecutionPolicy`确认一下是不是remotesigned，按理说如果是的话是可以执行本地脚本的

**Comment by Daniels5** [comment]
尝试了显示是remotesigned，截图到typora的时候还是原来权限不足的弹窗。在不同WIN10电脑操作都是同样的结果：（

**Comment by Daniels5** [comment]
运行 "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser"后取得了LocalMachine权限，并且以管理员身份运行qiniu-image-upload脚本问题后，QQ截图可以成功一键插入Markdown，成功使用：）

**Comment by MaNongkuxingseng** [comment]
@Daniels5 你好，以管理员身份运行qiniu-image-upload脚本后这这个是怎么运行的？在ps中还是cmd中？我都提示无法运行此文件。
