### ISSUE TITLE
报拒绝访问的错误

### ISSUE THREAD

**Issue by xiaoheifish** [jiwenxing/qiniu-image-tool-win#35]
win10系统，按照说明修改了ACCESS_KEY，SECRET_KEY，BUCKET_NAME 和BUCKET_DOMAIN。同时使用命令行启动powershell修改了权限。复制图片后，按ctrl + alt + v 上传时，命令行报的错误是拒绝访问。请问这个错误该如何解决啊？

**Comment by jiwenxing** [comment]
以管理员身份运行qImage.exe试试

**Comment by xiaoheifish** [comment]
> 以管理员身份运行qImage.exe试试
每次都是以管理员身份运行的，错误也都是拒绝访问，没有更详细的提示了。

**Comment by jiwenxing** [comment]
把报错的截图发一下看看？

**Comment by xiaoheifish** [comment]
> 把报错的截图发一下看看？


重启了电脑，可以正常使用了，非常感谢~
