### ISSUE TITLE
上传图片，报需要管理员权限打开powershell错误，设置管理员权限，依然重复出现

### ISSUE THREAD

**Issue by zengyaoliang** [jiwenxing/qiniu-image-tool-win#4]
set-executionpolicy : 对注册表项“HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Micro
soft.PowerShell”的访问被拒绝。 要更改默认(LocalMachine)作用域的执行策略，请使用“以管理员身份运行
”选项启动 Windows PowerShell。要更改当前用户的执行策略，请运行 "Set-ExecutionPolicy -Scope Current
User"。
所在位置 行:1 字符: 1
+ set-executionpolicy remotesigned
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessExcep
   tion
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.Set
   ExecutionPolicyCommand

**Comment by jiwenxing** [comment]
请参考 #3

**Comment by zengyaoliang** [comment]
参考 #3 把问题解决了。很好很强大，终于可以开开心心的写md文章了

**Comment by jiwenxing** [comment]
因为这个问题我在win7上没有遇到过，你能不能把你的解决过程大概写一下，我加到FAQ方便别人参考~

**Comment by MaNongkuxingseng** [comment]
@zengyaoliang 我跟你一样在windows powershell中设置有已显示权限为remotesigned，并且用管理员身份运行后任然出现：'powershell' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
你是怎么解决的？望赐教
